#include "codegen.h"
#include "string.h"
#include "vga.h"
#include <stddef.h>

#define CODEGEN_BUF_SIZE 16384

codegen_t *codegen_create(void) {
    static codegen_t cg;
    static char buf[CODEGEN_BUF_SIZE];
    memset(&cg, 0, sizeof(codegen_t));
    memset(buf, 0, CODEGEN_BUF_SIZE);
    cg.output = buf;
    cg.output_size = CODEGEN_BUF_SIZE;
    return &cg;
}

void codegen_destroy(codegen_t *cg) { (void)cg; }

const char *codegen_get_output(codegen_t *cg) { return cg->output; }

static void emit_str(codegen_t *cg, const char *s) {
    while (*s && cg->output_pos < cg->output_size - 1) {
        cg->output[cg->output_pos++] = *s++;
    }
    cg->output[cg->output_pos] = 0;
}

static void emit_line(codegen_t *cg, const char *s) {
    emit_str(cg, s);
    emit_str(cg, "\n");
}

static int int_to_str(int v, char *buf) {
    if (v == 0) { buf[0] = '0'; buf[1] = 0; return 1; }
    int neg = 0;
    if (v < 0) { neg = 1; v = -v; }
    char tmp[16]; int tn = 0;
    while (v > 0) { tmp[tn++] = '0' + (v % 10); v /= 10; }
    int i = 0;
    if (neg) buf[i++] = '-';
    for (int j = tn - 1; j >= 0; j--) buf[i++] = tmp[j];
    buf[i] = 0;
    return i;
}

static void gen_label(codegen_t *cg, char *buf, const char *prefix) {
    int n = 0;
    buf[n++] = '.';
    buf[n++] = 'L';
    char tmp[16];
    int_to_str(cg->label_counter++, tmp);
    int i = 0; while (tmp[i] && n < 28) buf[n++] = tmp[i++];
    if (prefix) {
        buf[n++] = '_';
        i = 0;
        while (prefix[i] && n < 31) buf[n++] = prefix[i++];
    }
    buf[n] = 0;
}

static void strncopy_local(char *dst, const char *src, int max) {
    int i = 0;
    while (src[i] && i < max - 1) { dst[i] = src[i]; i++; }
    dst[i] = 0;
}

static void gen_function(codegen_t *cg, ast_node_t *func);
static void gen_compound(codegen_t *cg, ast_node_t *comp);
static void gen_statement(codegen_t *cg, ast_node_t *stmt);
static void gen_expression(codegen_t *cg, ast_node_t *expr);
static void gen_declaration(codegen_t *cg, ast_node_t *decl);
static void gen_if(codegen_t *cg, ast_node_t *ifnode);
static void gen_while(codegen_t *cg, ast_node_t *whilenode);
static void gen_for(codegen_t *cg, ast_node_t *fornode);
static void gen_return(codegen_t *cg, ast_node_t *ret);
static void gen_assignment(codegen_t *cg, ast_node_t *assign);
static void gen_binary_op(codegen_t *cg, ast_node_t *op);
static void gen_function_call(codegen_t *cg, ast_node_t *call);

#define MAX_VARS 64
typedef struct {
    char name[32];
    int offset;
} var_t;
static var_t vars[MAX_VARS];
static int var_count;

static int find_var(const char *name) {
    for (int i = 0; i < var_count; i++) {
        if (strcmp(vars[i].name, name) == 0) return vars[i].offset;
    }
    return 0;
}

static int alloc_var(const char *name) {
    for (int i = 0; i < var_count; i++) {
        if (strcmp(vars[i].name, name) == 0) return vars[i].offset;
    }
    if (var_count >= MAX_VARS) return 0;
    int offset = (var_count + 1) * 4;
    strncopy_local(vars[var_count].name, name, 32);
    vars[var_count].offset = offset;
    var_count++;
    return offset;
}

int codegen_program(codegen_t *cg, ast_node_t *program) {
    emit_line(cg, "; Generated by occ (OaSis C Compiler)");
    emit_line(cg, "");

    ast_node_t *func = program->left;
    while (func) {
        gen_function(cg, func);
        emit_line(cg, "");
        func = func->right;
    }
    return cg->has_error ? -1 : 0;
}

static void emit_store_var(codegen_t *cg, int offset) {
    char buf[64];
    char off_str[16];
    int_to_str(offset, off_str);
    int bi = 0;
    const char *prefix = "  mov [ebp-";
    int pi = 0;
    while (prefix[pi] && bi < 60) buf[bi++] = prefix[pi++];
    int oi = 0;
    while (off_str[oi] && bi < 60) buf[bi++] = off_str[oi++];
    const char *suffix = "], eax";
    int si = 0;
    while (suffix[si] && bi < 63) buf[bi++] = suffix[si++];
    buf[bi] = 0;
    emit_line(cg, buf);
}

static void emit_load_var(codegen_t *cg, int offset) {
    char buf[64];
    char off_str[16];
    int_to_str(offset, off_str);
    int bi = 0;
    const char *prefix = "  mov eax, [ebp-";
    int pi = 0;
    while (prefix[pi] && bi < 60) buf[bi++] = prefix[pi++];
    int oi = 0;
    while (off_str[oi] && bi < 60) buf[bi++] = off_str[oi++];
    const char *suffix = "]";
    int si = 0;
    while (suffix[si] && bi < 63) buf[bi++] = suffix[si++];
    buf[bi] = 0;
    emit_line(cg, buf);
}

static void gen_function(codegen_t *cg, ast_node_t *func) {
    var_count = 0;
    strncopy_local(cg->current_func, func->string_value, 64);

    char label[64];
    label[0] = '_';
    int li = 1;
    char *fn = func->string_value;
    int fi = 0;
    while (fn[fi] && li < 63) { label[li++] = fn[fi++]; }
    label[li] = 0;
    emit_str(cg, label);
    emit_line(cg, ":");

    emit_line(cg, "  push ebp");
    emit_line(cg, "  mov ebp, esp");

    emit_str(cg, "  sub esp, ");
    int num_start = cg->output_pos;
    emit_str(cg, "X");
    emit_line(cg, "  ; stack for locals");

    /* Load parameters from stack (passed via [ebp+8], [ebp+12], etc) */
    int param_offset = 8; /* first param at [ebp+8] */
    ast_node_t *param = func->params;
    while (param) {
        int pv = alloc_var(param->string_value);
        if (param_offset == 8) {
            /* First param: already on stack */
        }
        char tmp_str[16];
        int_to_str(param_offset, tmp_str);
        emit_str(cg, "  mov eax, [ebp + "); emit_str(cg, tmp_str); emit_line(cg, "]");
        emit_store_var(cg, pv);
        param = param->right;
        param_offset += 4;
    }

    gen_compound(cg, func->body);

    int stack_size = var_count * 4;
    char stack_str[16];
    int_to_str(stack_size, stack_str);
    int slen = (int)strlen(stack_str);
    for (int i = 0; i < slen; i++) cg->output[num_start + i] = stack_str[i];
    cg->output[num_start + slen] = ' ';

    emit_line(cg, "  mov esp, ebp");
    emit_line(cg, "  pop ebp");
    emit_line(cg, "  ret");
}

static void gen_compound(codegen_t *cg, ast_node_t *comp) {
    ast_node_t *stmt = comp->left;
    while (stmt) {
        gen_statement(cg, stmt);
        stmt = stmt->right;
    }
}

static void gen_statement(codegen_t *cg, ast_node_t *stmt) {
    if (!stmt) return;
    switch (stmt->type) {
        case AST_DECLARATION: gen_declaration(cg, stmt); break;
        case AST_ASSIGNMENT:
        case AST_IF:          gen_if(cg, stmt); break;
        case AST_WHILE:       gen_while(cg, stmt); break;
        case AST_FOR:          gen_for(cg, stmt); break;
        case AST_RETURN:      gen_return(cg, stmt); break;
        case AST_COMPOUND:    gen_compound(cg, stmt); break;
        case AST_CALL:        gen_function_call(cg, stmt); break;
        default:              gen_expression(cg, stmt); emit_line(cg, "  ; expr stmt"); break;
    }
}

static void gen_declaration(codegen_t *cg, ast_node_t *decl) {
    int offset = alloc_var(decl->string_value);
    if (decl->right) {
        gen_expression(cg, decl->right);
        emit_store_var(cg, offset);
    }
}

static void gen_assignment(codegen_t *cg, ast_node_t *assign) {
    gen_expression(cg, assign->right);
    int offset = find_var(assign->string_value);
    emit_store_var(cg, offset);
}

static void gen_if(codegen_t *cg, ast_node_t *ifnode) {
    char else_label[32], end_label[32];
    gen_label(cg, else_label, "else");
    gen_label(cg, end_label, "endif");

    gen_expression(cg, ifnode->condition);
    emit_line(cg, "  cmp eax, 0");
    emit_str(cg, "  je ");
    emit_str(cg, else_label);
    emit_line(cg, "");

    gen_statement(cg, ifnode->body);

    if (ifnode->else_body) {
        emit_str(cg, "  jmp ");
        emit_str(cg, end_label);
        emit_line(cg, "");
        emit_str(cg, else_label);
        emit_line(cg, ":");
        gen_statement(cg, ifnode->else_body);
        emit_str(cg, end_label);
        emit_line(cg, ":");
    } else {
        emit_str(cg, else_label);
        emit_line(cg, ":");
    }
}

static void gen_while(codegen_t *cg, ast_node_t *whilenode) {
    char top_label[32], end_label[32];
    gen_label(cg, top_label, "while");
    gen_label(cg, end_label, "endw");

    emit_str(cg, top_label);
    emit_line(cg, ":");
    gen_expression(cg, whilenode->condition);
    emit_line(cg, "  cmp eax, 0");
    emit_str(cg, "  je ");
    emit_str(cg, end_label);
    emit_line(cg, "");
    gen_statement(cg, whilenode->body);
    emit_str(cg, "  jmp ");
    emit_str(cg, top_label);
    emit_line(cg, "");
    emit_str(cg, end_label);
    emit_line(cg, ":");
}

static void gen_for(codegen_t *cg, ast_node_t *fornode) {
    char loop_label[32], end_label[32];
    gen_label(cg, loop_label, "forlp");
    gen_label(cg, end_label, "forend");

    /* Init */
    if (fornode->left) {
        gen_expression(cg, fornode->left);
        /* Init biasanya assignment, hasil di eax bisa diabaikan */
    }

    emit_str(cg, loop_label);
    emit_line(cg, ":");

    /* Condition */
    if (fornode->condition) {
        gen_expression(cg, fornode->condition);
    } else {
        emit_line(cg, "  mov eax, 1");
    }
    emit_line(cg, "  cmp eax, 0");
    emit_str(cg, "  je ");
    emit_str(cg, end_label);
    emit_line(cg, "");

    /* Body */
    gen_statement(cg, fornode->body);

    /* Increment */
    if (fornode->right) {
        gen_expression(cg, fornode->right);
    }

    emit_str(cg, "  jmp ");
    emit_str(cg, loop_label);
    emit_line(cg, "");
    emit_str(cg, end_label);
    emit_line(cg, ":");
}

static void gen_return(codegen_t *cg, ast_node_t *ret) {
    if (ret->left) {
        gen_expression(cg, ret->left);
    } else {
        emit_line(cg, "  mov eax, 0");
    }
    emit_line(cg, "  mov esp, ebp");
    emit_line(cg, "  pop ebp");
    emit_line(cg, "  ret");
}

static void gen_expression(codegen_t *cg, ast_node_t *expr) {
    if (!expr) {
        emit_line(cg, "  mov eax, 0");
        return;
    }
    switch (expr->type) {
        case AST_INTEGER_LITERAL: {
            char buf[32];
            char num_str[16];
            int_to_str(expr->int_value, num_str);
            int bi = 0;
            const char *prefix = "  mov eax, ";
            int pi = 0;
            while (prefix[pi] && bi < 30) buf[bi++] = prefix[pi++];
            int ni = 0;
            while (num_str[ni] && bi < 30) buf[bi++] = num_str[ni++];
            buf[bi] = 0;
            emit_line(cg, buf);
            break;
        }
        case AST_STRING_LITERAL: {
            /*
             * String literal: emit data inline + jump over it.
             */
            char str_label[32], end_label[32];
            gen_label(cg, str_label, "str");
            gen_label(cg, end_label, "strend");

            /* jump over string data */
            emit_str(cg, "  jmp ");
            emit_line(cg, end_label);

            /* string data label */
            emit_str(cg, str_label);
            emit_line(cg, ":");

            /* emit db as comma separated hex values to avoid quote issues */
            emit_str(cg, "  db ");
            if (expr->string_value) {
                int first = 1;
                for (int si = 0; expr->string_value[si]; si++) {
                    if (!first) emit_str(cg, ", ");
                    first = 0;

                    char sc = expr->string_value[si];
                    if (sc == '\\' && expr->string_value[si+1]) {
                        si++;
                        switch (expr->string_value[si]) {
                            case 'n': emit_str(cg, "10"); break;
                            case 't': emit_str(cg, "9"); break;
                            case '\\': emit_str(cg, "92"); break;
                            case '0': emit_str(cg, "0"); break;
                            default: {
                                char buf[16];
                                int_to_str((unsigned char)expr->string_value[si], buf);
                                emit_str(cg, buf);
                                break;
                            }
                        }
                    } else {
                        char buf[16];
                        int_to_str((unsigned char)sc, buf);
                        emit_str(cg, buf);
                    }
                }
                if (!first) emit_str(cg, ", ");
            }
            /* null terminator */
            emit_line(cg, "0");

            /* end label */
            emit_str(cg, end_label);
            emit_line(cg, ":");

            /* load address of string into eax */
            emit_str(cg, "  mov eax, ");
            emit_line(cg, str_label);
            break;
        }
        case AST_IDENTIFIER: {
            int offset = find_var(expr->string_value);
            emit_load_var(cg, offset);
            break;
        }
        case AST_BINARY_OP:
            gen_binary_op(cg, expr);
            break;
        case AST_CALL:
            gen_function_call(cg, expr);
            break;
        case AST_ARRAY_SUBSCRIPT: {
            /* array[index] - access array element */
            gen_expression(cg, expr->left);  /* index expression */
            emit_line(cg, "  shl eax, 2");   /* index * 4 (sizeof int) */
            int v = find_var(expr->string_value);
            if (v >= 0) {
                char b[16]; int_to_str(v, b);
                emit_str(cg, "  lea ebx, [ebp - "); emit_str(cg, b); emit_line(cg, "]");
                emit_line(cg, "  mov eax, [ebx + eax]");
            } else {
                emit_str(cg, "  mov eax, ["); emit_str(cg, expr->string_value); emit_line(cg, " + eax * 4]");
            }
            break;
        }
        case AST_ASSIGNMENT:
            gen_assignment(cg, expr);
            break;
        default:
            emit_line(cg, "  mov eax, 0  ; unknown expr");
            break;
    }
}

static void gen_binary_op(codegen_t *cg, ast_node_t *op) {
    gen_expression(cg, op->left);
    emit_line(cg, "  push eax");
    gen_expression(cg, op->right);
    emit_line(cg, "  pop ebx");

    switch (op->op) {
        case TOKEN_PLUS:
            emit_line(cg, "  add eax, ebx");
            break;
        case TOKEN_MINUS:
            emit_line(cg, "  sub ebx, eax");
            emit_line(cg, "  mov eax, ebx");
            break;
        case TOKEN_STAR:
            emit_line(cg, "  imul eax, ebx");
            break;
        case TOKEN_SLASH:
            emit_line(cg, "  cdq");
            emit_line(cg, "  idiv ebx");
            break;
        case TOKEN_EQUAL:
            emit_line(cg, "  cmp eax, ebx");
            emit_line(cg, "  sete al");
            emit_line(cg, "  movzx eax, al");
            break;
        case TOKEN_NOT_EQUAL:
            emit_line(cg, "  cmp eax, ebx");
            emit_line(cg, "  setne al");
            emit_line(cg, "  movzx eax, al");
            break;
        case TOKEN_LESS:
            emit_line(cg, "  cmp ebx, eax");
            emit_line(cg, "  setl al");
            emit_line(cg, "  movzx eax, al");
            break;
        case TOKEN_LESS_EQUAL:
            emit_line(cg, "  cmp ebx, eax");
            emit_line(cg, "  setle al");
            emit_line(cg, "  movzx eax, al");
            break;
        case TOKEN_GREATER:
            emit_line(cg, "  cmp ebx, eax");
            emit_line(cg, "  setg al");
            emit_line(cg, "  movzx eax, al");
            break;
        case TOKEN_GREATER_EQUAL:
            emit_line(cg, "  cmp ebx, eax");
            emit_line(cg, "  setge al");
            emit_line(cg, "  movzx eax, al");
            break;
        default:
            emit_line(cg, "  ; unsupported op");
            break;
    }
}

static void gen_function_call(codegen_t *cg, ast_node_t *call) {
    int arg_count = 0;
    ast_node_t *arg = call->left;
    while (arg) {
        arg_count++;
        arg = arg->right;
    }

    if (arg_count > 0) {
        ast_node_t *args[8];
        int n = 0;
        arg = call->left;
        while (arg && n < 8) {
            args[n++] = arg;
            arg = arg->right;
        }
        for (int i = n - 1; i >= 0; i--) {
            gen_expression(cg, args[i]);
            emit_line(cg, "  push eax");
        }
    }

    emit_str(cg, "  call _");
    emit_str(cg, call->string_value);
    emit_line(cg, "");

    if (arg_count > 0) {
        char cleanup[32];
        char num_str[16];
        int_to_str(arg_count * 4, num_str);
        int bi = 0;
        const char *prefix = "  add esp, ";
        int pi = 0;
        while (prefix[pi] && bi < 30) cleanup[bi++] = prefix[pi++];
        int ni = 0;
        while (num_str[ni] && bi < 30) cleanup[bi++] = num_str[ni++];
        cleanup[bi] = 0;
        emit_line(cg, cleanup);
    }
}
