title: "OaSis OS Documentation"
description: "OaSis — x86 32-bit operating system from scratch"
baseurl: ""
url: "https://oasis.fariqdoing.tech"
markdown: kramdown
highlighter: rouge
permalink: pretty

nav:
  - title: Overview
    url: /
  - title: Pendahuluan
    url: /01-pendahuluan/
  - title: Arsitektur
    url: /02-arsitektur/
  - title: Booting
    url: /03-booting/
  - title: Kernel
    url: /04-kernel/
  - title: Driver
    url: /05-driver/
  - title: Filesystem
    url: /06-filesystem/
  - title: Shell
    url: /07-shell/
  - title: Aplikasi
    url: /08-apps/
  - title: Build
    url: /09-build/
  - title: Changelog
    url: /10-changelog/
